# Generated by Django 5.1.3 on 2025-02-14 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopZenApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='prixTotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
