# Generated by Django 5.1.3 on 2025-02-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopZenApp', '0002_alter_achat_prixtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='prixTotal',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(null=True, upload_to='categories'),
        ),
    ]
