# Generated by Django 5.1.3 on 2025-02-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopZenApp', '0003_alter_achat_prixtotal_alter_categorie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories'),
        ),
    ]
