# Generated by Django 5.1.3 on 2025-02-20 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ShopZenApp', '0006_alter_achat_modepayement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='modePayement',
            field=models.CharField(choices=[('En spece', 'En spece'), ('carte_credit', 'Carte de crédit'), ('tmoney', 'TMoney'), ('flooz', 'Flooz')], default='En spece', max_length=20),
        ),
        migrations.AlterField(
            model_name='achat',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achat', to='ShopZenApp.produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='quantite',
            field=models.PositiveIntegerField(),
        ),
    ]
